runs: 1
epochs: 5
earlystop_threshold: 5

wandb:
  enable: True
  api_key: 123
  entity: chtc-ospool-error-classification
  project: distributed-ml
  sweep:
    name: Osiris
    method: random
    metric:
      name: f-measure
      goal: maximize
  sweep_id: None
  run_id: None

preprocessing:
  parameters:
    j: # number of jobs for context window
      distribution: int_uniform
      min: 10
      max: 100
    m: # number of timeframes in a job matrix
      distribution: int_uniform
      min: 10
      max: 100
    timeframe_len: # duration of a single timeframe in seconds
      distribution: int_uniform
      min: 60
      max: 400

training:
  parameters:
    lstm_layers:
      values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    hidden_size:
      values: [16, 32, 64, 128]
    learning_rate:
      distribution: uniform
      min: 0.0
      max: 0.1
    batch_size:
      distribution: q_log_uniform_values
      q: 8
      min: 32
      max: 256
