name: hello world sweep
method: random
metric: 
  name: validate_loss
  goal: minimize
parameters:
  lstm_layers: 
    values: [1, 2, 3, 4, 5]
  hidden_size:
    values: [16, 32, 64, 128]
  learning_rate:
    distribution: uniform
    min: 0.0
    max: 0.1
  batch_size:
    distribution: q_log_uniform_values
    q: 8
    min: 32
    max: 256
  epochs:
    value: 25