runs: 50
epochs: 50

wandb:
  enable: True
  api_key: 10fd308beb114f4db7cd37b13cc74e953bf48b68
  entity: chtc-ospool-error-classification
  project: distributed-ml
  sweep:
    name: megatron
    method: random
    metric:
      name: validate_loss
      goal: minimize
  sweep_id: None
  run_id: None

preprocessing:
  parameters:
    j: # number of jobs for context window
      distribution: int_uniform
      min: 7
      max: 13
    m: # number of timeframes in a job matrix
      distribution: int_uniform
      min: 7
      max: 13
    timeframe_len: # duration of a single timeframe in seconds
      distribution: int_uniform
      min: 60
      max: 300

training:
  parameters:
    lstm_layers:
      values: [1, 2, 3, 4, 5]
    hidden_size:
      values: [16, 32, 64, 128]
    learning_rate:
      distribution: uniform
      min: 0.0
      max: 0.1
    batch_size:
      distribution: q_log_uniform_values
      q: 8
      min: 32
      max: 256
